apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
  - git:
      repoURL: https://github.com/jr-b/homelab-k8s.git
      revision: main
      directories:
      # STEP 1: Only cert-manager, external-dns, gateway, and CRDs
      - path: infrastructure/controllers/cert-manager
      - path: infrastructure/controllers/external-dns
      # - path: infrastructure/controllers/intel-device-plugins  # [DISABLED FOR STEP 1]
      # - path: infrastructure/controllers/node-feature-discovery  # [DISABLED FOR STEP 1]
      # - path: infrastructure/networking/coredns  # [DISABLED FOR STEP 1]
      - path: infrastructure/networking/gateway
      # - path: infrastructure/storage/container-registry  # [DISABLED FOR STEP 1]
      # - path: infrastructure/storage/csi-driver-nfs  # [DISABLED FOR STEP 1]
      # - path: infrastructure/storage/csi-driver-smb  # [DISABLED FOR STEP 1]
      # - path: infrastructure/storage/local-storage  # [DISABLED FOR STEP 1]
      # - path: infrastructure/storage/openebs  # [DISABLED FOR STEP 1]
      # - path: infrastructure/database/*/*  # [DISABLED FOR STEP 1]
      - path: infrastructure/crds
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        app.kubernetes.io/part-of: infrastructure
    spec:
      project: infrastructure
      revisionHistoryLimit: 3
      source:
        repoURL: https://github.com/jr-b/homelab-k8s.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
        - Replace=false
        - IgnoreMissingTemplate=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      ignoreDifferences:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        jsonPointers:
        - /spec/rules/0/backendRefs/0/group
        - /spec/rules/0/backendRefs/0/kind
        - /spec/rules/0/backendRefs/0/weight
      - group: gateway.networking.k8s.io
        kind: Gateway
        jsonPointers:
        - /status
      - group: postgresql.cnpg.io
        kind: Cluster
        jsonPointers:
        - /status
        - /metadata/generation
      - group: external-secrets.io
        kind: ExternalSecret
        jsonPointers:
        - /status

